services:
  mailculator-dev:
    build:
      context: .
      target: dev
    volumes:
      - .:/app
      - /app/go/pkg
    ports:
      - "8080:8080"
    command: ["air"]

  mailculator-prod:
    build:
      context: .
      target: prod
    ports:
      - "8080:8080"
